### ISSUE TITLE
Unhandled rejection NoSuchKey: The specified key does not exist.

### ISSUE THREAD

**Issue by HareshChhelana** [sambaiz/puppeteer-lambda-starter-kit#12]
When i try to run code on AWS Lambda getting below error. Additional your code contain Async / Promise which is supported node >=7, So i have use asyncawit and promise npm to make code work on 6.10 without any syntax error. 

2018-02-07T11:57:17.215Z	0a5ce928-0bfe-11e8-baa4-a70b2f9693d9	Unhandled rejection NoSuchKey: The specified key does not exist.
    at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/services/s3.js:577:35)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)
END RequestId: 0a5ce928-0bfe-11e8-baa4-a70b2f9693d9

**Comment by lucianw** [comment]
I had the same problem. In my case, I had not configured my VPC correctly in order for my Lambda Function to have access to the internet.

You should check out [this article](https://docs.aws.amazon.com/lambda/latest/dg/vpc.html#vpc-internet).
After I had configured my VPC correctly (2 private subnets, 1 public subnet) and added only the two private subnets to my Lambda Function, I was able to access the Internet from within and the S3 Download started working too.
